-- Supabase PostgreSQL Migration for AI-Powered Interview Practice Platform
-- Run this in the Supabase SQL Editor (https://supabase.com -> Project -> SQL Editor)

-- 1. Create users table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  target_role TEXT DEFAULT 'Full Stack Developer',
  experience_level TEXT DEFAULT 'Mid-Level (3-5 years)',
  industry TEXT DEFAULT 'Software & Technology',
  bio TEXT DEFAULT '',
  skills_json TEXT DEFAULT '[]',
  target_jd TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create interview_sessions table
CREATE TABLE IF NOT EXISTS public.interview_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  target_role TEXT NOT NULL,
  experience_level TEXT NOT NULL,
  industry TEXT NOT NULL,
  interview_type TEXT NOT NULL,
  job_description TEXT DEFAULT '',
  status TEXT DEFAULT 'in_progress',
  overall_score INT DEFAULT 0,
  duration_seconds INT DEFAULT 0,
  summary TEXT DEFAULT '',
  strengths_json TEXT DEFAULT '[]',
  weaknesses_json TEXT DEFAULT '[]',
  improvement_plan_json TEXT DEFAULT '[]',
  role_explanation TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create questions table
CREATE TABLE IF NOT EXISTS public.questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES public.interview_sessions(id) ON DELETE CASCADE,
  question_number INT NOT NULL,
  question_text TEXT NOT NULL,
  category TEXT NOT NULL,
  difficulty TEXT NOT NULL,
  expected_competencies_json TEXT DEFAULT '[]',
  star_guidance TEXT DEFAULT '',
  is_follow_up INT DEFAULT 0,
  parent_question_id BIGINT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create answers table
CREATE TABLE IF NOT EXISTS public.answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  answer_text TEXT NOT NULL,
  duration_seconds INT DEFAULT 0,
  self_assessment_score INT DEFAULT 3,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create feedback table
CREATE TABLE IF NOT EXISTS public.feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answer_id BIGINT UNIQUE NOT NULL REFERENCES public.answers(id) ON DELETE CASCADE,
  relevance_score INT NOT NULL,
  clarity_score INT NOT NULL,
  evidence_score INT NOT NULL,
  star_score INT NOT NULL,
  confidence_score INT NOT NULL,
  overall_score INT NOT NULL,
  feedback_summary TEXT NOT NULL,
  star_breakdown_json TEXT NOT NULL,
  improved_star_response TEXT NOT NULL,
  strengths_json TEXT DEFAULT '[]',
  areas_for_improvement_json TEXT DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Create prep_cards table
CREATE TABLE IF NOT EXISTS public.prep_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  session_id BIGINT DEFAULT NULL REFERENCES public.interview_sessions(id) ON DELETE CASCADE,
  card_type TEXT NOT NULL,
  title TEXT NOT NULL,
  content_json TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Create session_shares table
CREATE TABLE IF NOT EXISTS public.session_shares (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES public.interview_sessions(id) ON DELETE CASCADE,
  shared_by_user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  shared_with_email TEXT NOT NULL,
  share_code TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Create practice_plans table
CREATE TABLE IF NOT EXISTS public.practice_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  session_id BIGINT DEFAULT NULL REFERENCES public.interview_sessions(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  plan_days_json TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interview_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prep_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.practice_plans ENABLE ROW LEVEL SECURITY;

-- Allow Service Role full access to all tables
CREATE POLICY "Service Role full access on users" ON public.users FOR ALL USING (true);
CREATE POLICY "Service Role full access on interview_sessions" ON public.interview_sessions FOR ALL USING (true);
CREATE POLICY "Service Role full access on questions" ON public.questions FOR ALL USING (true);
CREATE POLICY "Service Role full access on answers" ON public.answers FOR ALL USING (true);
CREATE POLICY "Service Role full access on feedback" ON public.feedback FOR ALL USING (true);
CREATE POLICY "Service Role full access on prep_cards" ON public.prep_cards FOR ALL USING (true);
CREATE POLICY "Service Role full access on session_shares" ON public.session_shares FOR ALL USING (true);
CREATE POLICY "Service Role full access on practice_plans" ON public.practice_plans FOR ALL USING (true);

-- Create performance indexes
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON public.interview_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_questions_session_id ON public.questions(session_id);
CREATE INDEX IF NOT EXISTS idx_answers_question_id ON public.answers(question_id);
CREATE INDEX IF NOT EXISTS idx_session_shares_code ON public.session_shares(share_code);
